apiVersion: v1
kind: Pod
metadata:
  name: another-fedora-physnet
  annotations:
    switches: a-physnet-switch
    k8s.v1.cni.cncf.io/networks: an-ovn-physnet
    ovn_extra: '{"a-physnet-switch":{"mac_address":"0a:00:00:00:00:03"}}'
spec:
  containers:
  - name: fedora
    image: yuvalif/fedora-tcpdump
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
    resources:
      limits:
        memory: "128Mi"
    command: ["sleep", "1000"]
